name: Apache Webserver
description: |
  Apache Stuff
defaultVersion: v1.5.4-vancher1-1
category: Apache
maintainer: "Amy Chen <amy@rancher.com>"
minimum_rancher_version: v1.5.0
license: Apache License
project_URL: https://httpd.apache.org/
