version: '2'
services:
  apache-server:
    image: httpd:2.4.25
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - php
  php:
    image: php:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro