version: '2'
services:
  apache:
    image: php:apache
    volumes:
      - content:/var/www/html/
    ports:
      - "8080:80"
  apache-lb:
    image: rancher/lb-service-haproxy:latest
    ports:
      - 80
volumes: 
  content:
    driver: rancher-nfs
