version: '2'
catalog:
  name: Apache
  version: 2017-03-29-rancher1
  questions:
    - variable: "VOLUME_DRIVER"
      description: "Docker driver to store volume or base path for each disk"
      label: "Volume driver / Path"
      type: "string"
      required: true
      default: "local"
    - variable: "APACHE_SCALE"
      description: "Number of apache nodes."
      label: "Apache Nodes"
      required: true
      default: 1
      type: int

services:
  apache:
    scale: ${APACHE_SCALE}
  apache-lb:
    scale: 1
    lb_config:
      port_rules:
        - source_port: 80
          target_port: 8080
          service: apache
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000