version: '2'
catalog:
  name: Apache
  version: v4.3.17-rancher1
  description: "Serves PHP web apps populated in volume"
  minimum_rancher_version: v1.5.0
  questions:
    - variable: "APACHE_SCALE"
      description: "Number of Apache nodes"
      label: "Apache nodes"
      type: int
      required: true
      default: 1
    - variable: "VOLUME_DRIVER"
      description: "Docker volume driver"
      label: "Volume Driver"
      type: "string"
      default: "local"
    - variable: "PUBLISH_PORT"
      description: "Customize your external publish port, defaults to port 80"
      label: "Publish Port"
      type: int
      required: false
      default: 80
    - variable: "PROTOCOL"
      description: "Specify your load balancer communication protocol"
      label: "Protocol"
      type: enum
      required: false
      default: http
      options:
        - ""
        - http
        - tcp
        - https
        - tls
        - sni
        - custom
    - variable: "CERT_NAME"
      description: "Specify certificate name created in Rancher UI. Mandatory for https, tls, and sni protocols."
      label: "Certificate Name"
      type: certificate
      required: false
    - variable: "CUSTOM"
      description: "Enter your custom load balancer config here for custom protocol"
      label: "Custom load balancer config"
      type: multiline
      required: false
    - variable: "APACHE_CONF"
      description: "Enter your apache configuration file here"
      label: "Apache Configuration"
      type: multiline
      required: false
    - variable: "APACHE_CERT"
      description: "Certificate for SSL termination in Apache server"
      label: "Apache SSL Certificate"
      type: multiline
      required: false
    - variable: "APACHE_KEY"
      description: "Key for SSL termination in Apache server"
      label: "Apache SSL Key"
      type: multiline
      required: false
