version: '2'
catalog:
  name: "labels test"
  version: "2.0.0"
  questions:
    - variable: "test"
      description: "Host label where to run traefik service."
      label: "Host label:"
      required: true
      default: "traefik_lb=true" 
      type: "multiline"